window.QDMB_CONFIG = Object.freeze({
  SUPABASE_URL: 'YOUR_SUPABASE_URL',
  SUPABASE_KEY: 'YOUR_SUPABASE_PUBLISHABLE_KEY',
  ADMIN_EMAIL: 'admin@example.com',
  GUILD_NAME: 'CARTOON NETWORK',
  PAGE_TITLE: 'BÁO CÁO TUYỂN THÀNH VIÊN MỚI',
});
