-- QDMB / GitHub Pages + Supabase setup
-- Authorization uses auth.users.raw_app_meta_data.role = 'admin'.
create extension if not exists pgcrypto;

create table if not exists public.members (
  id uuid primary key default gen_random_uuid(),
  id_code text not null unique,
  name text not null,
  facebook_url text not null,
  profile_url text,
  profile_path text,
  joined_at date not null,
  status text not null default 'dat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.members add column if not exists status text not null default 'dat';
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'members_status_check') then
    alter table public.members add constraint members_status_check check (status in ('dat','khong_dat','thoat'));
  end if;
end $$;

create or replace function public.set_members_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists members_set_updated_at on public.members;
create trigger members_set_updated_at before update on public.members for each row execute function public.set_members_updated_at();

create table if not exists public.member_status_logs (
  id bigint generated by default as identity primary key,
  member_id uuid references public.members(id) on delete set null,
  member_name text not null,
  id_code text,
  old_status text not null check (old_status in ('dat','khong_dat','thoat')),
  new_status text not null check (new_status in ('dat','khong_dat','thoat')),
  changed_at timestamptz not null default now()
);
create index if not exists member_status_logs_changed_at_idx on public.member_status_logs(changed_at desc);

create or replace function public.log_member_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.status is distinct from new.status then
    insert into public.member_status_logs(member_id, member_name, id_code, old_status, new_status)
    values (new.id, new.name, new.id_code, old.status, new.status);
  end if;
  return new;
end;
$$;
revoke execute on function public.log_member_status_change() from public, anon, authenticated;
drop trigger if exists members_log_status_change on public.members;
create trigger members_log_status_change after update of status on public.members for each row execute function public.log_member_status_change();

alter table public.members enable row level security;
alter table public.member_status_logs enable row level security;
grant select on table public.members to anon;
grant select, insert, update, delete on table public.members to authenticated;
grant select on table public.member_status_logs to anon, authenticated;

drop policy if exists "public read members" on public.members;
create policy "public read members" on public.members for select to anon using (true);
drop policy if exists "authenticated read members" on public.members;
create policy "authenticated read members" on public.members for select to authenticated using (true);
drop policy if exists "admin insert members" on public.members;
create policy "admin insert members" on public.members for insert to authenticated with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "admin update members" on public.members;
create policy "admin update members" on public.members for update to authenticated using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin') with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "admin delete members" on public.members;
create policy "admin delete members" on public.members for delete to authenticated using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "public read member status logs" on public.member_status_logs;
create policy "public read member status logs" on public.member_status_logs for select to anon using (true);
drop policy if exists "authenticated read member status logs" on public.member_status_logs;
create policy "authenticated read member status logs" on public.member_status_logs for select to authenticated using (true);

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('member-profiles','member-profiles',true,5242880,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "admin read profile objects" on storage.objects;
create policy "admin read profile objects" on storage.objects for select to authenticated using (bucket_id='member-profiles' and (((select auth.jwt()) -> 'app_metadata' ->> 'role')='admin'));
drop policy if exists "admin upload profile objects" on storage.objects;
create policy "admin upload profile objects" on storage.objects for insert to authenticated with check (bucket_id='member-profiles' and (((select auth.jwt()) -> 'app_metadata' ->> 'role')='admin'));
drop policy if exists "admin update profile objects" on storage.objects;
create policy "admin update profile objects" on storage.objects for update to authenticated using (bucket_id='member-profiles' and (((select auth.jwt()) -> 'app_metadata' ->> 'role')='admin')) with check (bucket_id='member-profiles' and (((select auth.jwt()) -> 'app_metadata' ->> 'role')='admin'));
drop policy if exists "admin delete profile objects" on storage.objects;
create policy "admin delete profile objects" on storage.objects for delete to authenticated using (bucket_id='member-profiles' and (((select auth.jwt()) -> 'app_metadata' ->> 'role')='admin'));

do $$ begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='members') then
    execute 'alter publication supabase_realtime add table public.members';
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='member_status_logs') then
    execute 'alter publication supabase_realtime add table public.member_status_logs';
  end if;
end $$;
